route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "autoscaler"

receivers:
  - name: "autoscaler"
    webhook_configs:
      - url: "http://autoscaler:5050/scale"
