global:
  scrape_interval: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "docker"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values: [prometheus.scrape="true"]
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_port]
        target_label: __metrics_path__
        replacement: /metrics
      - source_labels: [__meta_docker_container_label_prometheus_port]
        target_label: __address__
        replacement: ${1}:${2}

  - job_name: "nodejs"
    static_configs:
      - targets: ["api:5000", "image-generator:4000"]
    metrics_path: "/metrics"
