/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesMineImport } from './routes/recipes/mine'
import { Route as RecipesCreateImport } from './routes/recipes/create'
import { Route as RecipesIdImport } from './routes/recipes/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesMineRoute = RecipesMineImport.update({
  path: '/recipes/mine',
  getParentRoute: () => rootRoute,
} as any)

const RecipesCreateRoute = RecipesCreateImport.update({
  path: '/recipes/create',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIdRoute = RecipesIdImport.update({
  path: '/recipes/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdImport
      parentRoute: typeof rootRoute
    }
    '/recipes/create': {
      id: '/recipes/create'
      path: '/recipes/create'
      fullPath: '/recipes/create'
      preLoaderRoute: typeof RecipesCreateImport
      parentRoute: typeof rootRoute
    }
    '/recipes/mine': {
      id: '/recipes/mine'
      path: '/recipes/mine'
      fullPath: '/recipes/mine'
      preLoaderRoute: typeof RecipesMineImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/mine': typeof RecipesMineRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/mine': typeof RecipesMineRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/mine': typeof RecipesMineRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes/$id' | '/recipes/create' | '/recipes/mine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes/$id' | '/recipes/create' | '/recipes/mine'
  id: '__root__' | '/' | '/recipes/$id' | '/recipes/create' | '/recipes/mine'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIdRoute: typeof RecipesIdRoute
  RecipesCreateRoute: typeof RecipesCreateRoute
  RecipesMineRoute: typeof RecipesMineRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIdRoute: RecipesIdRoute,
  RecipesCreateRoute: RecipesCreateRoute,
  RecipesMineRoute: RecipesMineRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/recipes/$id",
        "/recipes/create",
        "/recipes/mine"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/recipes/$id": {
      "filePath": "recipes/$id.tsx"
    },
    "/recipes/create": {
      "filePath": "recipes/create.tsx"
    },
    "/recipes/mine": {
      "filePath": "recipes/mine.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
